DIVISIONS = ["Makuuchi", "Juryo", "Makushita", "Sandanme", "Jonidan", "Jonokuchi"]

MAKUUCHI_RANKS = ["Maegashira", "Komusubi", "Sekiwake", "Ozeki", "Yokozuna"]

BASE_URL = "https://sumodb.sumogames.de"

JAPAN, MONGOLIA, GEORGIA, BULGARIA, CHINA = "Japan", "Mongolia", "Georgia", "Bulgaria", "China"

JAPAN_PREFECTURES = [
    'Hokkaido', 'Aomori', 'Iwate', 'Miyagi', 'Akita', 'Yamagata', 'Fukushima',
    'Ibaraki', 'Tochigi', 'Gunma', 'Saitama', 'Chiba', 'Tokyo', 'Kanagawa',
    'Niigata', 'Toyama', 'Ishikawa', 'Fukui', 'Yamanashi', 'Nagano', 'Gifu',
    'Shizuoka', 'Aichi', 'Mie', 'Shiga', 'Kyoto', 'Osaka', 'Hyogo', 'Nara',
    'Wakayama', 'Tottori', 'Shimane', 'Okayama', 'Hiroshima', 'Yamaguchi',
    'Tokushima', 'Kagawa', 'Ehime', 'Kochi', 'Fukuoka', 'Saga', 'Nagasaki',
    'Kumamoto', 'Oita', 'Miyazaki', 'Kagoshima', 'Okinawa'
]

KIMARITES = list(
    map(
        lambda x: x.lower(),
        [
            "Abisetaoshi",
            "Oshidashi",
            "Oshitaoshi",
            "Tsukidashi",
            "Tsukitaoshi",
            "Yorikiri",
            "Yoritaoshi",
            "Ashitori",
            "Chongake",
            "Kawazugake",
            "Kekaeshi",
            "Ketaguri",
            "Kirikaeshi",
            "Komatasukui",
            "Kozumatori",
            "Mitokorozeme",
            "Nimaigeri",
            "Ōmata",
            "Sotogake",
            "Sotokomata",
            "Susoharai",
            "Susotori",
            "Tsumatori",
            "Uchigake",
            "Watashikomi",
            "Ipponzeoi",
            "Kakenage",
            "Koshinage",
            "Kotenage",
            "Kubinage",
            "Nichōnage",
            "Shitatedashinage",
            "Shitatenage",
            "Sukuinage",
            "Tsukaminage",
            "Uwatedashinage",
            "Uwatenage",
            "Yaguranage",
            "Amiuchi",
            "Gasshōhineri",
            "Harimanage",
            "Kainahineri",
            "Katasukashi",
            "Kotehineri",
            "Kubihineri",
            "Makiotoshi",
            "Ōsakate",
            "Sabaori",
            "Sakatottari",
            "Shitatehineri",
            "Sotomusō",
            "Tokkurinage",
            "Tottari",
            "Tsukiotoshi",
            "Uchimusō",
            "Uwatehineri",
            "Zubuneri",
            "Izori",
            "Kakezori",
            "Shumokuzori",
            "Sototasukizori",
            "Tasukizori",
            "Tsutaezori",
            "Hatakikomi",
            "Hikiotoshi",
            "Hikkake",
            "Kimedashi",
            "Kimetaoshi",
            "Okuridashi",
            "Okurigake",
            "Okurihikiotoshi",
            "Okurinage",
            "Okuritaoshi",
            "Okuritsuridashi",
            "Okuritsuriotoshi",
            "Sokubiotoshi",
            "Tsuridashi",
            "Tsuriotoshi",
            "Ushiromotare",
            "Utchari",
            "Waridashi",
            "Yobimodoshi",
            "Fumidashi",
            "Isamiashi",
            "Koshikudake",
            "Tsukihiza",
            "Tsukite",
            "Fusen",
            "Hansoku",
        ],
    )
)
